const movieTitles = [
  "Mayabazar",
  "Nuvvu Naaku Nachav",
  "Khushi",
  "Aithe",
  "Anand",
  "Manmadhudu",
  "Okkadu",
  "Athadu",
  "Bommarillu",
  "Pokiri",

  "Jalsa",
  "Happy Days",
  "Arya",
  "Godavari",
  "Shankar Dada MBBS",
  "Magadheera",
  "Kick",
  "Ye Maaya Chesave",
  "Vedam",
  "Leader",

  "Eega",
  "Gabbar Singh",
  "Julayi",
  "Pelli Choopulu",
  "Kshanam",
  "Arjun Reddy",
  "Rangasthalam",
  "Mahanati",
  "Goodachari",
  "C/o Kancharapalem",

  "Jersey",
  "Agent Sai Srinivasa Athreya",
  "Mathu Vadalara",
  "Ala Vaikunthapurramuloo",
  "Sarileru Neekevvaru",
  "Jathi Ratnalu",
  "Uppena",
  "Sita Ramam",
  "Major",
  "RRR",

  "Pushpa: The Rise",
  "Dasara",
  "Hi Nanna",
  "Balagam",
  "MAD",
  "Virupaksha",
  "Karthikeya 2",
  "DJ Tillu",
  "Brochevarevarura",
  "Ee Nagaraniki Emaindi"
];

export default movieTitles;